### ISSUE TITLE
Whitespace on console

### ISSUE THREAD

**Issue by DRTEK** [kontaxis/snidump#4]
Hello 
thank you for the program 
Sometimes i get many whitespaces on the console and it seems that program goes in to loop 
i tried it on 2 different pcs same thing happens 
it happens specially when code was executed right after it was exited .
thanks

**Comment by kontaxis** [comment]
Can you give more information to reproduce this issue?

Which platform are you running it on?
What's the input?
What's the output?
How do you terminate the program?

Thanks
