### ISSUE TITLE
referer field along with host field in http log in snidump

### ISSUE THREAD

**Issue by ravin22** [kontaxis/snidump#5]
Hi, I am using your snidump to log tls as well http packets , in case of http packets snidump logs host value only out of payload.

Is it possible to extract referer value out of payload and print along with host value ?

Thanks for such useful tool.

**Comment by kontaxis** [comment]
You can change the regular expression in http_init() to match the Referer in addition to the Host header field.

`-       const char *regex_HTTP_RequestHeaderHost = "^Host:[ ]*([^ ]+)[ ]*\r\n";`
`+       const char *regex_HTTP_RequestHeaderHost = "^(?:Referer|Host):[ ]*([^ ]+)[ ]*\r\n";`

**Comment by ravin22** [comment]
Hi

thanks for following up on this, I did what you have mentioned in the mail
but it still prints only hostname in the logs.

Can you please lookup on this ?

Regards

Ravin

**Comment by kontaxis** [comment]
What does snidump print when you execute the following command?

`curl -e http://www.google.com http://www.example.com -o /dev/null`

**Comment by ravin22** [comment]
nothing it stays blank

**Comment by kontaxis** [comment]
Are you using the default BPF? Are you listening on the correct interface? Usually eth0.

**Comment by ravin22** [comment]
this is how i run snidump

./snidump -p -i wlan0

as mentioned in README.md

**Comment by kontaxis** [comment]
Are you using the wireless interface (wlan0) to access the Internet?

**Comment by ravin22** [comment]
running this curl -e http://www.google.com http://www.stackoverflow.com -o
/dev/null

shows in sndump

10.1.1.99:56134 -> 151.101.1.69:[80] 21:www.stackoverflow.com
10.1.1.99:56134 -> 151.101.1.69:[80] 21:http://www.google.com


10.1.1.99 is my ip

**Comment by ravin22** [comment]
yes wlan0 what happened ?

**Comment by kontaxis** [comment]
The second line is your referrer, is it not? You can tell them apart because Host field values do not have the scheme.

**Comment by ravin22** [comment]
Well let me verify it again then

Thanks

**Comment by ravin22** [comment]
running curl -e http://www.google.com http://www.stackoverflow.com -o
/dev/null

prints payload in http.c as

GET / HTTP/1.1
User-Agent: curl/7.38.0
Host: www.stackoverflow.com
Accept: */*
Referer: http://www.google.com


which in snidump logs shows as

10.1.1.99:56134 -> 151.101.1.69:[80] 21:www.stackoverflow.com
10.1.1.99:56134 -> 151.101.1.69:[80] 21:http://www.google.com


But when i actually opens stackoverflow in my web browser

payload is

GET / HTTP/1.1
Host: stackoverflow.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101
Firefox/48.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://stackoverflow.com/
Cookie: _ga=GA1.2.598140162.1429593463;
acct=t=YS5wW22Qp%2fsrsjvuWi0oAakYW3MDpM0z&s=Z%2bdx%2fnBCajo6tHvDd05sM16HBGqAT%2f8P;
prov=75dee5ab-b84c-4079-9705-60ae988f33e0;
__qca=P0-1575456964-1468828252858; cc=ef8eda33795e41e1919e6f2e82a2ced3;
csouser=t=7HquIsKCSUmv&s=0qGkPdqtgEa7; _gat=1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

And in this case it prints

10.1.1.99:39353 -> 151.101.65.69:[80] 17:stackoverflow.com

only

Can you verify it by running on your side?

**Comment by ravin22** [comment]
This isn't working in case when we actually opens webpage and fetch the
actual referer out of the http header.

**Comment by kontaxis** [comment]
Typo in the code introduced a bug where parsing misbehaved when the request was beyond a certain size. curl requests are much smaller than those of web browsers. The Host field is usually very close to the beginning of the request so it wasn't affected. This is not true for the Referer field. Looking for the referrer made the bug show up. Please pull the latest version and try again.

**Comment by ravin22** [comment]
okay I will try with the new version

Thanks!

**Comment by ravin22** [comment]
Works Fine Now
Keep it up!!
