### ISSUE TITLE
Fetching GET request from payload results in segmention fault

### ISSUE THREAD

**Issue by ravin22** [kontaxis/snidump#6]
Hi 
I am trying to fetch the GET request from snidump and for that i have included following code in http.c
it is working fine till i get normal requests  like this 

payload is now GET /m HTTP/1.1
Host: www.google.co.in
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
User-Agent: UCWEB/2.0(Linux; U; Opera Mini/7.1.32052/30.3697; en-US; HTC Desire 828 dual sim Build/LMY47D) U2/1.0.0 UCBrowser/10.9.0.731 Mobile
Connection: keep-alive
X-UCBrowser-UA: dv(HTC Desire 828 dual sim);pr(UCBrowser/10.9.0.731);ov(Android 5.1);ss(360_592);pi(1080_1776);bt(GJ);pm(1);bv(1);nm(0);im(0);sr(0);nt(2);dn();ai(720089404747345);
Accept-Encoding: gzip
Accept-Language: en-US

But segmentation fault occurs when this happens or something like this

payload is GET /gdt_mview.fcg?datatype=2&posid=5010810193388558&count=4&r=0.31287740599398406&adposcount=1&ext=%7B%22req%22%3A%7B%22scs%22%3A%2200014eb238db%22%2C%22conn%22%3A1%2C%22muidtype%22%3A1%2C%22c_market%22%3A%22%22%2C%22ast%22%3A%7B%22de%22%3A%22A94%22%2C%22is_d%22%3Afalse%2C%22hw%22%3A%22java%22%2C%22br%22%3A%22Micromax%22%2C%22sr%22%3A%22J42V3MC21ES16650%22%2C%22pr%22%3A%22A94%22%2C%22fp%22%3A%22Micromax%5C%2FA94%5C%2FA94%3A4.2.2%5C%2FA94%5C%2F20140305.142119%3Auser%5C%2Frelease-keys%22%7D%2C%22lng%22%3A75584834%2C%22c_w%22%3A320%2C%22c_device%22%3A%22Micromax%20A94%22%2C%22c_osver%22%3A%224.2.2%22%2C%22tmpallpt%22%3Atrue%2C%22carrier%22%3A0%2C%22c_pkgname%22%3A%22com.lenovo.anyshare%22%2C%22c_os%22%3A%22android%22%2C%22c_h%22%3A569%2C%22lat%22%3A31319202%2C%22c_devicetype%22%3A1%2C%22sdkver%22%3A%224.8%22%2C%22m1%22%3A%22eac69c37f59c4eb94305ceb3ca8a87bb%22%2C%22m2%22%3A%22f76f874bb2869801c1f4ea786ead77f1%22%2C%22m3%22%3A%226a07eb94932f1152d2c36556d2c16740%22%2C%22muid%22%3A%22eac69c37f59c4eb94305ceb3ca8a87bb%22%2C%22c_mf%22%3A%22Micromax%22%2C%22location_accuracy%22%3A37%2C%22postype%22%3A8%2C%22c_sdfree%22%3A1211957248%2C%22deep_link_version%22%3A1%2C%22gdtid%22%3A%22eac69c37f59c4eb94305ceb3ca8a87bb_1472716878659%22%2C%22c_ori%22%3A0%7D%7D HTTP/1.1
User-Agent: GDTADNetClient-[Dalvik/1.6.0 (Linux; U; Android 4.2.2; Micromax A94 Build/A94)]
Accept-Encoding: gzip
Host: mi.gdt.qq.com
Connection: Keep-Alive

Sorry for the mess.
here is the modified http.c including GET request code.
[http.zip](https://github.com/kontaxis/snidump/files/449116/http.zip)

Can you please check this?

**Comment by kontaxis** [comment]
Is this an issue with the original code? Looks like you've made quite a few changes.

**Comment by ravin22** [comment]
I just made changes related to get the GET request only just like it does for HOST rest is same 
segmentation faults occurs when it tries to run pcre_exec to fetch the GET "...."  

Is it suitable to do so or how else i can get this?
