### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by bonki** [kontaxis/snidump#7]
Thanks for this, works like a charm!

However, right now it's unclear under which terms you share your code, can you add licensing information?

**Comment by garo** [comment]
Also wanted to thank you for this tool and yes, please add a license =)

**Comment by bonki** [comment]
Bump!

**Comment by kontaxis** [comment]
Fixed in https://github.com/kontaxis/snidump/commit/84266b364f01d99965f71bb9646639cb537c8872
