### ISSUE TITLE
Segmentation Fault in http_process_request

### ISSUE THREAD

**Issue by ravin22** [kontaxis/snidump#8]
Hi,
I have noticed segmentation fault while snidump checks "The current line ends at the sequence \r\n"  in for loop in http_process_request of src/http.c file.

Here is the output of gdb
Program received signal SIGSEGV, Segmentation fault.
0x000000000040455c in http_process_request (
    payload=0x7ffff551d088 "POST /mistats/v2 HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Redmi 3S MIUI/V8.0.3.0.MALMIDG)\r\nHost: data.mistat.xiaomi.com\r\nConnection"..., payload_length=1158) at src/http.c:170
170			if (headers[i] != '\n' || i == 0 || headers[i - 1] != '\r') {

Can you please check why snidump failed at the if-statement ?

**Comment by kontaxis** [comment]
Have you made any changes to the code?

And can you provide a pcap file with the input that causes the crash?

**Comment by ravin22** [comment]
Hi
I have made few changes in it, I am testing it further,segfault was due to changes I have made I guess ?

**Comment by kontaxis** [comment]
I can only address issues with the original code.

Closing this issue.

Can you please file a new issue if you are able to reproduce the crash in the original code, i.e., the code pulled from GitHub without any changes?
